# # Publish all joint states -----------------------------------
# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 50

# Trajectory Controllers
tohoku_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - MFRAME
    - BLOCK
    - BOOM
    - ARM
    - TOHKU_PITCH
    - TOHKU_ROLL
  gains:
    MFRAME: {p: 50, i: 200, d: 0, i_clamp: 0}
    BLOCK: {p: 50, i: 200, d: 0, i_clamp: 0}
    BOOM: {p: 50, i: 200, d: 0, i_clamp: 0}
    ARM: {p: 50, i: 200, d: 0, i_clamp: 0}
    TOHKU_PITCH: {p: 50, i: 200, d: 0, i_clamp: 0}
    TOHKU_ROLL: {p: 50, i: 200, d: 0, i_clamp: 0}
mani_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - UFRAME
    - MNP_SWING
    - MANI_BOOM
    - MANIARM
    - MANIELBOW
    - YAWJOINT
    - HANDBASE
  gains:
    MFRAME: {p: 50, i: 200, d: 0, i_clamp: 0}
    BLOCK: {p: 50, i: 200, d: 0, i_clamp: 0}
    BOOM: {p: 50, i: 200, d: 0, i_clamp: 0}
    ARM: {p: 50, i: 200, d: 0, i_clamp: 0}
    TOHKU_PITCH: {p: 50, i: 200, d: 0, i_clamp: 0}
    TOHKU_ROLL: {p: 50, i: 200, d: 0, i_clamp: 0}
base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'WHEEL_L0'
  right_wheel : 'WHEEL_R0'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 1.2
  wheel_radius : 0.4

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0
  
  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 1.0
  
  # Base frame_id
  base_frame_id: base_footprint #default: base_link
  
  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 4.0
      min_velocity           : -4.0 # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.0  # m/s^2
    min_acceleration       : -1.0 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 6.28  # rad/s
      min_velocity           : -6.28
      has_acceleration_limits: true
      max_acceleration       : 1.57  # rad/s^2
      min_acceleration       : -1.57
